dev_tools_map:
    resource: "@DevToolsMapBundle/Resources/config/routing.yml"
    prefix:   /Map

birds_observations:
    resource: "@BirdsObservationsBundle/Resources/config/routing.yml"
    prefix:   /Obs

app:
    resource: '@AppBundle/Resources/config/routing.yml'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"