blog_home:
    path:     /{pageNumber}
    defaults: { _controller: DevToolsBlogBundle:Blog:home, pageNumber:1 }
    requirements:
        pageNumber: \d+

blog_article:
    path:     /article/{id}
    defaults: { _controller: DevToolsBlogBundle:Blog:readArticle }
    requirements:
        id:  \d+
blog_article_modif:
    path:     /article/{id}/modif
    defaults: { _controller: DevToolsBlogBundle:Blog:home }
    requirements:
        id:  \d+
blog_article_delete:
    path:     /article/{id}/delete
    defaults: { _controller: DevToolsBlogBundle:Blog:home }
    requirements:
        id:  \d+

blog_article_create:
    path:     /article/create
    defaults: { _controller: DevToolsBlogBundle:Blog:home }

