birds_observations:
    path:     /observations
    defaults: { _controller: BirdsObservationsBundle:Observation:observations }

birds_observations_add:
    path:     /add
    defaults: { _controller: BirdsObservationsBundle:Observation:addObs }

