
birds_observations:
    path:     /
    defaults: { _controller: BirdsObservationsBundle:Observation:observations }

birds_observation:
    path:     /observation/{id}
    defaults: { _controller: BirdsObservationsBundle:Observation:seeObservation }
    requirements:
        id : \d+

birds_observations_add:
    path:     /observation/create
    defaults: { _controller: BirdsObservationsBundle:Observation:addObs }

birds_observations_remove:
    path:     /observation/{id}/remove
    defaults: { _controller: BirdsObservationsBundle:Observation:deleteObservation }
    requirements:
        id : \d+

birds_observations_update:
    path:     /observation/{id}/modify
    defaults: { _controller: BirdsObservationsBundle:Observation:updateObservation }
    requirements:
        id : \d+

birds_my_observations:
    path:     /observation/me
    defaults: { _controller: BirdsObservationsBundle:Observation:myObservations }

birds_en_attente:
    path:     /OnHold
    defaults: { _controller: BirdsObservationsBundle:Observation:onHold }


API_birdname:
    path:     /API/birds
    defaults: {_controller: BirdsObservationsBundle:Observation:birdsJson }