
birds_observations:
    path:     /{page}/{limit}
    defaults:
        _controller: BirdsObservationsBundle:Observation:observations
        page: 1
        limit: 5
    requirements:
        page: \d*
        limit: \d+

birds_observations:
    path:     /{page}/{limit}/{research}/{minDate}/{{maxDate}/maxHours}/{minHours}/{latitude}/{longitude}/{radius}
    defaults:
        _controller: BirdsObservationsBundle:Observation:observations
        page: 1
        limit: 5
        minDate: "2017-09-01"
        minHours: 0
        maxHours: 23
    requirements:
        page: \d+
        limit: \d+


birds_treatsearch:
    path:   /searching
    defaults: {_controller: BirdsObservationsBundle:Observation:treatSearch }

birds_observation:
    path:     /observation/{id}
    defaults: { _controller: BirdsObservationsBundle:Observation:seeObservation }
    requirements:
        id : \d+

birds_observations_add:
    path:     /observation/create
    defaults: { _controller: BirdsObservationsBundle:Observation:addObs }

birds_observations_remove:
    path:     /observation/{id}/remove
    defaults: { _controller: BirdsObservationsBundle:Observation:deleteObservation }
    requirements:
        id : \d+

birds_observations_update:
    path:     /observation/{id}/modify
    defaults: { _controller: BirdsObservationsBundle:Observation:updateObservation }
    requirements:
        id : \d+

birds_my_observations:
    path:     /observation/me
    defaults: { _controller: BirdsObservationsBundle:Observation:myObservations }

birds_en_attente:
    path:     /OnHold
    defaults: { _controller: BirdsObservationsBundle:Observation:onHold }


API_birdname:
    path:     /API/birds
    defaults: {_controller: BirdsObservationsBundle:Observation:birdsJson }