home:
        path:   /
        defaults: { _controller: AppBundle:App:accueil }

mission:
        path:   /Mission
        defaults: { _controller: AppBundle:App:aPropos }

admin:
        path: /admin
        defaults: { _controller: AppBundle:App:adminHome }

admin_user:
        path: /admin/users
        defaults: { _controller: AppBundle:App:adminUsers }

admin_articles:
        path: /admin/articles
        defaults: { _controller: AppBundle:App:adminArticles }

admin_validate_user:
    path: /admin/{id}/validateUser
    defaults: { _controller: AppBundle:App:userValidate }
    requirements:
        id: \d+

admin_delete_user:
    path: /admin/{id}/delete
    defaults: { _controller: AppBundle:App:userDelete }
    requirements:
        id: \d+

admin_passobs_user:
    path: /admin/{id}/passObs
    defaults: { _controller: AppBundle:App:toObs }
    requirements:
        id: \d+
